inherit_from: configs/scannet/scannet.yaml
mapping:
  bound: [[-0.1,8.6],[-0.1,8.9],[-0.3,3.3]]
  marching_cubes_bound: [[-0.1,8.6],[-0.1,8.9],[-0.3,3.3]]
  keyframe_every: 1
  map_every: 1
  enable_replay: False
  mem_log_every: 20
  

mesh: 
  render_color: True
  vis: 50  

training:
  ewc_enabled: False
  ewc_lambda: 0.1
  temporal_consensus:
    enabled: True
    K: 1
    frames_per_task: 100
    inject_every: 2
    gamma: 1 
    uncertainty_decay: 0.99  


grid:
  hash_size: 16 # 1.59M
  

data:
  datadir: data/scannet/scene0000_00
  trainskip: 1
  output: output/scannet/scene0000_00
  exp_name: CADMM
  load_path: fixed_decoder.pt

tracking:
  gt_pose: True


multi_agents:
  num_agents: 1
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  #edges_for_dropout: [ [0,1,0.99], [0,2,0.99], [1,2,0.99] ] # [node i, node j, possibility of dropping out]
  edges_for_dropout: []
  distributed_algorithm: 'CADMM'
  rho: 0.0001
  track_uncertainty: True
  fix_decoder: True
  alpha: 0.15 # DSGD
  #alpha: 0.05 # DSGT

edge_based: True