inherit_from: configs/scannet/scannet.yaml
mapping:
  bound: [[-0.1,8.6],[-0.1,8.9],[-0.3,3.3]]
  marching_cubes_bound: [[-0.1,8.6],[-0.1,8.9],[-0.3,3.3]]
  keyframe_every: 1
  map_every: 1
  enable_replay: False
  mem_log_every: 20
  

mesh: 
  render_color: True
  vis: 50  

training:
  ewc_enabled: False
  ewc_lambda: 0.1

  mas_enabled: False
  mas:
    lambda: 1
    frames_per_task: 10

  mas_original_enabled: False
  mas_original:
    lambda: 1
    frames_per_task: 100
    buffer_size: 5

  kr_enabled: False
  kr:
    buffer_size: 10
    save_every: 50
    num_replay_rays: 512


  cnm_enabled: False
  cnm:
    frames_per_task: 100
    buffer_size: 200000
    num_samples_per_teacher: 200000
    num_offsurface_samples: 1024
    offsurface_weight: 0.01
    alpha: 6.0
    near_threshold: 0.05
    value_weight_near: 1.0
    value_weight_far: 0.1

  unikd_enabled: False  # Set to True to enable
  unikd:
    frames_per_task: 20      # Update teacher every 100 frames
    uncertainty_threshold: 0.05 # Threshold to filter teacher's bad predictions
    n_random_poses: 20        # Number of random poses to sample per distillation step
    eta: 0.1                  # Margin parameter in loss
    beta_min: 0.05            # Minimum uncertainty value

  temporal_consensus:
    enabled: True
    K: 1
    frames_per_task: 1
    inject_every: 1
    mask_threshold: 0



grid:
  hash_size: 16 # 1.59M
  

data:
  datadir: data/scannet/scene0000_00
  trainskip: 1
  output: output/scannet/scene0000_00
  exp_name: Ours_nomask
  load_path: fixed_decoder.pt

tracking:
  gt_pose: True


multi_agents:
  num_agents: 1
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  #edges_for_dropout: [ [0,1,0.99], [0,2,0.99], [1,2,0.99] ] # [node i, node j, possibility of dropping out]
  edges_for_dropout: []
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.01
  track_uncertainty: True
  fix_decoder: True
  alpha: 0.15 # DSGD
  #alpha: 0.05 # DSGT

edge_based: True