inherit_from: configs/scannet/scannet.yaml
mapping:
  bound: [[-0.1,8.6],[-0.1,8.9],[-0.3,3.3]]
  marching_cubes_bound: [[-0.1,8.6],[-0.1,8.9],[-0.3,3.3]]
  keyframe_every: 1
  map_every: 1
  enable_replay: False
  mem_log_every: 20
  

mesh: 
  render_color: True
  vis: 50  

training:
  ewc_enabled: False
  ewc_lambda: 0.1

  mas_enabled: False
  mas:
    lambda: 1           # MAS 正则系数 λ
    frames_per_task: 100  # 多少帧视为一个“任务”，在任务边界更新 Ω 和 θ*


  kr_enabled: False
  kr:
    K: 10 # 保留的关键帧个数
    num_replay_rays: 256 # 每次 BA 从这 K 个 KF 总共采样多少条射线


  cnm_enabled: False
  cnm:
    frames_per_task: 100
    buffer_size: 200000
    num_samples_per_teacher: 200000    # 每次 teacher 更新时生成的伪样本数
    num_offsurface_samples: 1024      # 每次 BA 取多少伪样本
    offsurface_weight: 0.01           # 整体 CNM loss 权重，建议先小一点
    alpha: 6.0                        # ψ_s 中的 α
    near_threshold: 0.05              # |sdf_old| < 0.05 视为 near-surface
    value_weight_near: 1.0            # near 区域 value consistency 权重
    value_weight_far: 0.1             # far 区域 value consistency 权重


  temporal_consensus:
    enabled: True
    K: 1
    frames_per_task: 10
    inject_every: 1
    gamma: 0.2 
    uncertainty_decay: 1.0


grid:
  hash_size: 16 # 1.59M
  

data:
  datadir: data/scannet/scene0000_00
  trainskip: 1
  output: output/scannet/scene0000_00
  exp_name: Ours(mas)_2_rho_0.1_frames15
  load_path: fixed_decoder.pt

tracking:
  gt_pose: True


multi_agents:
  num_agents: 1
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  #edges_for_dropout: [ [0,1,0.99], [0,2,0.99], [1,2,0.99] ] # [node i, node j, possibility of dropping out]
  edges_for_dropout: []
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.1
  track_uncertainty: True
  fix_decoder: True
  alpha: 0.15 # DSGD
  #alpha: 0.05 # DSGT

edge_based: True