inherit_from: configs/Replica/replica.yaml
mapping:
  # bound: [[-2,3.2],[-1.7,2.7],[-1.2,2.0]]
  # marching_cubes_bound: [[-1.9,3.1],[-1.6,2.6],[-1.1,1.8]]
  bound:  [[-3,3],[-3,3],[-0.5,1]] #VICON ROOM
  marching_cubes_bound:  [[-3,3],[-3,3],[-0.5,1]]
  keyframe_every: 1
  map_every: 1
  enable_replay: False
  mem_log_every: 20
  filter_depth: True
  iters: 10  # global BA iters, defaul 10
  first_iters: 200 # default 200 
  

mesh: 
  render_color: True
  vis: 100
  voxel: 0.05


cam: 
  H: 360
  W: 640

  # oogway
  fx: 498.37325
  fy: 498.37325
  cx: 327.03568499999994
  cy: 181.04722166666664

  crop_edge: 0
  near: 0
  far: 5
  depth_trunc: 100. # this is for calculating sdf loss. in m
  max_depth: 10000. # where I cut my depth pixel value


data:
  downsample: 1
  sc_factor: 1
  output: output/Replica/change_oogway
  exp_name: Ours_gammamask
  load_path: fixed_decoder.pt
  datadir: data/Replica/change_oogway
  trainskip: 1


training:
  rgb_weight: 5.0
  depth_weight: 0.1
  sdf_weight: 1000
  fs_weight: 10 # 10 by default
  smooth_weight: 0.000001

  ewc_enabled: False
  ewc_lambda: 30

  mas_enabled: False
  mas:
    lambda: 1           # MAS 正则系数 λ
    frames_per_task: 1  # 多少帧视为一个“任务”，在任务边界更新 Ω 和 θ*

  mas_original_enabled: False
  mas_original:
    lambda: 1           # 正则化系数
    frames_per_task: 100  # 多少帧触发一次离线计算
    buffer_size: 10       # Replay Buffer 大小 (每个任务最多存多少帧)

  kr_enabled: False
  kr:
    buffer_size: 10      # Buffer 最多存 10 帧
    save_every: 20       # 每 200 帧存一次 (Interval)
    num_replay_rays: 256 # 每次 BA 采样多少条射线

  cnm_enabled: False
  cnm:
    buffer_size: 200000       # 真实表面点 Buffer 大小
    pts_per_frame: 2000        # 每帧向 Buffer 添加多少个点 (Down-sampling)
    batch_size_zero: 2048    # 每次 BA 回放多少个表面点 (Zero level-set)
    batch_size_off: 4096      # 每次 BA 采样多少个随机离面点 (Off-surface)
    weight_zero: 1.0          # 表面回放 Loss 权重
    weight_sign: 0.01          # 符号正则化 Loss 权重
    alpha: 5              # 符号正则强度 (论文公式中的 alpha)
    update_freq: 20         # 每多少帧进行一次 CNM 更新
    epsilon: 0.05             # 符号正则平滑参数 (论文公式中的 ε)

  unikd_enabled: False  # Set to True to enable
  unikd:
    frames_per_task: 100      # Update teacher every n frames
    uncertainty_threshold: 0.05 # Threshold to filter teacher's bad predictions
    n_random_poses: 20        # Number of random poses to sample per distillation step
    eta: 0.1                  # Margin parameter in loss
    beta_min: 0.05            # Minimum uncertainty value

  temporal_consensus:
    enabled: True
    K: 1
    frames_per_task: 1
    inject_every: 1
    gamma: 1
    uncertainty_decay: 1
    mask_threshold: 0

multi_agents:
  num_agents: 1
  com_every: 1 
  distributed_algorithm: 'AUQ_CADMM'
  rho:  0.05
  track_uncertainty: True
  fix_decoder: True
  #alpha: 0.15 # DSGD
  alpha: 0.02 # DSGT
  complete_graph: True
  edges_for_dropout: []

tracking:
  gt_pose: True

edge_based: True