inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-5.6,1.4],[-3.2,2.8],[-1.6,1.8]]
  marching_cubes_bound: [[-5.6,1.4],[-3.2,2.8],[-1.6,1.8]]
  keyframe_every: 1
  map_every: 1
  enable_replay: False
  mem_log_every: 20


mesh: 
  render_color: True
  vis: 60  


training:

  ewc_enabled: False
  ewc_lambda: 1

  mas_enabled: False
  mas:
    lambda: 0.1           # MAS 正则系数 λ
    frames_per_task: 100  # 多少帧视为一个“任务”，在任务边界更新 Ω 和 θ*


  kr_enabled: False 
  kr:
    K: 10 # 保留的关键帧个数
    num_replay_rays: 256 # 每次 BA 从这 K 个 KF 总共采样多少条射线

  cnm_enabled: False
  cnm:
    frames_per_task: 500
    buffer_size: 20000        # 经验回放 buffer 大小
    num_samples_per_teacher: 20000    # 每次 teacher 更新时生成的伪样本数
    num_offsurface_samples: 256      # 每次 BA 取多少伪样本
    offsurface_weight: 0.1           # 整体 CNM loss 权重，建议先小一点
    alpha: 12.0                        # ψ_s 中的 α
    near_threshold: 0.05              # |sdf_old| < 0.05 视为 near-surface
    value_weight_near: 1.0            # near 区域 value consistency 权重
    value_weight_far: 0.1             # far 区域 value consistency 权重·、

  unikd_enabled: False  # Set to True to enable
  unikd:
    frames_per_task: 20      # Update teacher every 100 frames
    uncertainty_threshold: 0.05 # Threshold to filter teacher's bad predictions
    n_random_poses: 20        # Number of random poses to sample per distillation step
    eta: 0.1                  # Margin parameter in loss
    beta_min: 0.05            # Minimum uncertainty value

  temporal_consensus:
    enabled: True
    K: 1
    frames_per_task: 10
    inject_every: 1
    gamma: 0.2
    uncertainty_decay: 1.0

data:
  datadir: data/Replica/room1
  trainskip: 1
  output: output/Replica/room1
  exp_name: Ours
  load_path: fixed_decoder.pt


tracking:
  gt_pose: True


multi_agents:
  num_agents: 1
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  #edges_for_dropout: [ [0,1,0.5], [0,2,0.5], [1,2,0.5] ] # [node i, node j, possibility of dropping out]
  edges_for_dropout: []
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.1
  track_uncertainty: True
  fix_decoder: True
  alpha: 0.9 # DSGD
  #alpha: 0.10 # DSGT

edge_based: True