inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-1.0,7.0],[-1.3,3.7],[-1.7,1.4]]
  marching_cubes_bound: [[-1.0,7.0],[-1.3,3.7],[-1.7,1.4]]
  keyframe_every: 1
  map_every: 1
  enable_replay: False
  mem_log_every: 20


mesh: 
  render_color: True
  vis: 60  


training:

  ewc_enabled: False
  ewc_lambda: 30

  mas_enabled: True
  mas:
    lambda: 1           # MAS 正则系数 λ
    frames_per_task: 1  # 多少帧视为一个“任务”，在任务边界更新 Ω 和 θ*

  mas_original_enabled: False
  mas_original:
    lambda: 1           # 正则化系数
    frames_per_task: 100  # 多少帧触发一次离线计算
    buffer_size: 10       # Replay Buffer 大小 (每个任务最多存多少帧)

  kr_enabled: False
  kr:
    buffer_size: 10      # Buffer 最多存 10 帧
    save_every: 20       # 每 200 帧存一次 (Interval)
    num_replay_rays: 256 # 每次 BA 采样多少条射线

  cnm_enabled: False
  cnm:
    buffer_size: 200000       # 真实表面点 Buffer 大小
    pts_per_frame: 2000        # 每帧向 Buffer 添加多少个点 (Down-sampling)
    batch_size_zero: 2048    # 每次 BA 回放多少个表面点 (Zero level-set)
    batch_size_off: 4096      # 每次 BA 采样多少个随机离面点 (Off-surface)
    weight_zero: 1.0          # 表面回放 Loss 权重
    weight_sign: 0.01          # 符号正则化 Loss 权重
    alpha: 5              # 符号正则强度 (论文公式中的 alpha)
    update_freq: 20         # 每多少帧进行一次 CNM 更新
    epsilon: 0.05             # 符号正则平滑参数 (论文公式中的 ε)

  unikd_enabled: False  # Set to True to enable
  unikd:
    frames_per_task: 100      # Update teacher every n frames
    uncertainty_threshold: 0.05 # Threshold to filter teacher's bad predictions
    n_random_poses: 20        # Number of random poses to sample per distillation step
    eta: 0.1                  # Margin parameter in loss
    beta_min: 0.05            # Minimum uncertainty value

  temporal_consensus:
    enabled: False
    K: 1
    frames_per_task: 1
    inject_every: 1
    gamma: 1
    uncertainty_decay: 1 
    mask_threshold: 1e-4

data:
  datadir: data/Replica/room0
  trainskip: 1
  output: output/Replica/room0
  exp_name: Online_MAS
  load_path: fixed_decoder.pt


tracking:
  gt_pose: True


multi_agents:
  num_agents: 1
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  #edges_for_dropout: [ [0,1,0.5], [0,2,0.5], [1,2,0.5] ] # [node i, node j, possibility of dropping out]
  edges_for_dropout: []
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.005
  track_uncertainty: True
  fix_decoder: True
  alpha: 0.9 # DSGD
  #alpha: 0.10 # DSGT

edge_based: True