inherit_from: configs/Replica/replica.yaml
mapping:
  # bound: [[-2,3.2],[-1.7,2.7],[-1.2,2.0]]
  # marching_cubes_bound: [[-1.9,3.1],[-1.6,2.6],[-1.1,1.8]]
  bound:  [[-3,3],[-3,3],[-0.5,1]] #VICON ROOM
  marching_cubes_bound:  [[-3,3],[-3,3],[-0.5,1]]
  keyframe_every: 1
  map_every: 1
  

mesh: 
  render_color: True
  vis: 200
  voxel: 0.05


cam: 
  H: 360
  W: 640

  # oogway
  fx: 498.37325
  fy: 498.37325
  cx: 327.03568499999994
  cy: 181.04722166666664

  crop_edge: 0
  near: 0
  far: 5
  depth_trunc: 100. # this is for calculating sdf loss
  max_depth: 10000. # where I cut my depth pixel value


data:
  num_frames: 6000
  downsample: 1
  sc_factor: 1
  output: output/turtlebot
  exp_name: change_oogway
  load_path: fixed_decoder.pt


training:
  rgb_weight: 5.0
  depth_weight: 0.1
  sdf_weight: 1000
  fs_weight: 10 # 10 by default
  smooth_weight: 0.000001

multi_agents:
  com_every: 1 
  distributed_algorithm: 'CADMM'
  rho:  0.0001 
  track_uncertainty: True
  fix_decoder: False
  #alpha: 0.15 # DSGD
  alpha: 0.02 # DSGT

